force-app/main/default/objects/Log__e/Log__e.object-meta.xml
<CustomObject>
    <description>Even Logging</description>
    <label>Log</label>
    <pluralLabel>Logs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Log__e/fields/Salesforce_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Record_Id__c</fullName>
    <description>Salesforce Record Id</description>
    <label>Salesforce Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>Log source of event</description>
    <label>Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__c/LogEvent__c.object-meta.xml
<CustomObject>
    <label>Log Event</label>
    <nameField>
        <displayFormat>Log-{00000}</displayFormat>
        <label>Log Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LogEvent__c/fields/Log_Data__c.field-meta.xml
<CustomField>
    <fullName>Log_Data__c</fullName>
    <description
  >Log message, stack trace/dump, exception messages, user-defined text message</description>
    <label>Log Data</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/LogEvent__c/fields/Quiddity__c.field-meta.xml
<CustomField>
    <fullName>Quiddity__c</fullName>
    <description
  >Resource - https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_enum_System_Quiddity.htm</description>
    <label>Quiddity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__c/fields/Request_Id__c.field-meta.xml
<CustomField>
    <fullName>Request_Id__c</fullName>
    <description
  >Request ID, auto-populated when called from Apex Log or explicitly set when publishing Log__e directly</description>
    <label>Request Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__c/fields/Salesforce_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Record_Id__c</fullName>
    <description>Log Salesforce Record Id</description>
    <label>Salesforce Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogEvent__c/fields/Severity__c.field-meta.xml
<CustomField>
    <fullName>Severity__c</fullName>
    <description
  >Log Severity - INFO, WARNING, DEBUG, ERROR, follows standard Salesforce ENUMS</description>
    <label>Severity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DEBUG</fullName>
            </value>
            <value>
                <fullName>INFO</fullName>
            </value>
            <value>
                <fullName>WARN</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LogEvent__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description
  >Source of log event - e.g. Apex Class Name, Apex Method Name, Flow</description>
    <label>Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LogTriggerHandler.cls
/**
 * @description       : LogTriggerHandler
 * @author            : agentgill
 * @group             :
 * @last modified on  : 03-26-2021
 * @last modified by  : agentgill
 * Modifications Log
 * Ver   Date         Author      Modification
 * 1.0   02-18-2021   agentgill   Initial Version
 **/
public inherited sharing class LogTriggerHandler extends TriggerHandler {
  List<Log__e> incomingRecords = new List<Log__e>();

  /**
   * @description Contructor
   * @author agentgill | 02-18-2021
   **/
  public LogTriggerHandler() {
    this.incomingRecords = (List<Log__e>) Trigger.new;
    System.debug(LoggingLevel.ERROR, '>>>' + incomingRecords);
  }

  /**
   * @description after Insert
   * @author agentgill | 02-18-2021
   **/
  override public void afterInsert() {
    List<LogEvent__c> events = new List<LogEvent__c>();

    for (Log__e event : this.incomingRecords) {
      events.add(
        new LogEvent__c(
          Log_Data__c = event.Log_Message__c,
          Quiddity__c = event.Quiddity__c,
          Request_Id__c = event.request_id__c,
          Severity__c = event.severity__c,
          Source__c = event.Source__c,
          Salesforce_Record_Id__c = event.Salesforce_Record_Id__c
        )
      );
    }

    List<Database.SaveResult> res = Database.insert(events, false);
    for (Database.SaveResult saveRes : res) {
      if (!saveRes.isSuccess()) {
        System.debug(
          LoggingLevel.ERROR,
          'Failed to save log message: ' + saveRes
        );
      }
    }
  }
}